create table noteful_folders (
    id integer primary key generated by default as identity,
    folder_name text not null
);

create table noteful_notes (
    id integer primary key generated by default as identity,
    note_name text not null,
    content text,
    modified_date timestamp default now() not null,
    folder_id integer not null --references noteful_folders(id) on delete cascade not null
);

alter table noteful_notes
    add constraint constraint_fk
    foreign key (folder_id)
    references noteful_folders(id)
    on delete cascade;